# Generated by Django 6.0.2 on 2026-02-04 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.FloatField(help_text='CGPA (5.0 to 10.0)')),
                ('skills_score', models.IntegerField(help_text='Skills rating (1-10)')),
                ('projects', models.IntegerField(help_text='Number of projects')),
                ('internship', models.IntegerField(help_text='0=No, 1=Yes')),
                ('certifications', models.IntegerField(help_text='Number of certs')),
                ('predicted_score', models.FloatField(help_text='Predicted score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
